### ISSUE TITLE
[Bug]: Both lost impossible outcome

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

In 2 competitions, both groups lost, and that is not possible.

![Screenshot 2023-09-03 at 13 21 20](https://github.com/Betarena/scores/assets/37311649/c0b96e28-1373-4511-ad77-9b15593e8e05)

### 🤔 Expected Behavior

Only one group can lose.

### What environment is the bug/issue detected in.

- [ ] Production (scores.betarena.com)
- [X] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

Visit:

https://betarena-scores-platform.herokuapp.com/competitions/predictor/team-hantharwady-united-will-win/41

**Comment by migbash** [comment]
**🔸 UPDATE**

This is caused by the new (latest) addition of the `data.winner_group (property)` that contains the target team that `won/lost`. Upon adding this field to the `(competition) id: 41` and with the correct `(competition) data.status: "finished"` state, the UI correctly shows the `WON / LOST` states for each respective vote.

@jonsnowpt Although not expected to occur, but if `winner_group` has an error, or is not available, like in this case, should the `WON / LOST` not be shown ?
