### ISSUE TITLE
[Bug]: Competitions lobby just showing the first 4 finished

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

Missing all competitions besides the first 4 in the finished section, and new open competitions are not visible.

### 🤔 Expected Behavior

Show all finished competitions in the lobby.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

**Comment by migbash** [comment]
> Missing all competitions besides the first 4 in the finished section [..]

Caused by the repetitive use of the `cache` and the missing `[..]&hasura=true` query flag on the endpoint `GET` for data regarding `competition | highlights`. Adjustments made to properly address the correct flag use and clearer options passing to said methods that handle `_this_` data pagination.

> **Note**
> Created offspring task ➤ #<-github-issue-number->.
> Created offspring task ➤ #<-github-issue-number->.

> **Note**
> Corrected, awaiting `🚀 deployment`.

> [..] new open competitions are not visible.

Caused by incorrect `triggers` of data for update. Needs to be looked at.
